### ISSUE TITLE
Default locale to english

### ISSUE THREAD

**Issue by nagamohanm** [buhichan/rehooker-schema-form#3]
Hi,

Is there anyway we can use this with English as default. If yes, can you let me know how to go about doing it.

Thank you in advance.

**Comment by buhichan** [comment]
**Thanks for your issue!**

I think i didn't get what you mean by locale.

If you mean the label above each input widgets, it's the label property in the "schema" (provided by you) of `<ReduxSchemaForm schema={schema} />`
```
const schema = [
    {
       key:"name",
       type:"text",
       label:"Name" // or "なまえ"
    }
]
```

If you mean the locale used in date and datetime widgets:
- material-ui theme: I just added "okLabel", "cancelLabel" and "locale" property in schema definition.
- and.design theme: [check their docs](https://ant.design/components/locale-provider/)
- you can always overwrite any widgets by use the exposed "addType" method
```
import {addType,WidgetProps} from "redux-schema-form"

class CustomWidget extends React.PureComponent<WidgetProps>{
    render(){
        ...
    }
}

addType("datetime")(CustomWidget)
```
